module.exports = {
  LOGIN: "LOGIN",
  PURCHASED_ITEMS: "PURCHASED_ITEMS",
  SUBMIT_FEEDBACK: "SUBMIT_FEEDBACK",
  FEEDBACK_DETAILS: "FEEDBACK_DETAILS",
  DISC_PDT: "DISC_PDT",
  LOGOUT: "LOGOUT",
  FB_ID: "FB_ID",
  PRODUCT_DETAILS:"PRODUCT_DETAILS",
};
